//引入资源
import logo from './souce/logo.png';
import banner from './souce/banner.jpg';
import home from './souce/home.png';
import home_click from './souce/home_click.png';
import warehousing from './souce/warehousing.png';
import warehousing_click from './souce/warehousing_click.png';
import outgoing from './souce/outgoing.png';
import outgoing_click from './souce/outgoing_click.png';
import commodity from './souce/commodity.png';
import commodity_click from './souce/commodity_click.png';
import stock from './souce/stock.png';
import stock_click from './souce/stock_click.png';
import customer from './souce/customer.png';
import customer_click from './souce/customer_click.png';
import system from './souce/system.png';
import system_click from './souce/system_click.png';
import home_in from './souce/home_in.png';
import home_out from './souce/home_out.png';
import home_repo from './souce/home_repo.png';
import client_list from './souce/client_list.png';
import warehousing_business from './souce/warehousing_business.png';
import outbound_business from './souce/outbound_business.png';
import user_management from './souce/user_management.png';
import change_password from './souce/change_password.png';
import stock_search from './souce/stock_search.png';
import commodity_management from './souce/commodity_management.png';
import role_management from './souce/role_management.png';
import logo2 from './souce/csj-logo2.png';
import loginBg from './souce/login_bg.png';
import qrcode from './souce/qrcode.jpg';
import tools from './souce/tools.png';

const imgSouce = {};
//挂载资源
imgSouce['logo'] = logo;
imgSouce['tools_click'] = tools;
imgSouce['logo2'] = logo2;
imgSouce['banner'] = banner;
imgSouce['loginBg'] = loginBg;
imgSouce['qrcode'] = qrcode;
imgSouce['home'] = home;
imgSouce['home_click'] = home_click;
imgSouce['warehousing'] = warehousing;
imgSouce['warehousing_click'] = warehousing_click;
imgSouce['outgoing'] = outgoing;
imgSouce['outgoing_click'] = outgoing_click;
imgSouce['commodity'] = commodity;
imgSouce['commodity_click'] = commodity_click;
imgSouce['stock'] = stock;
imgSouce['stock_click'] = stock_click;
imgSouce['customer'] = customer;
imgSouce['customer_click'] = customer_click;
imgSouce['system'] = system;
imgSouce['system_click'] = system_click;
imgSouce['home_in'] = home_in;
imgSouce['home_out'] = home_out;
imgSouce['home_repo'] = home_repo;
imgSouce['client_list'] = client_list;
imgSouce['warehousing_business'] = warehousing_business;
imgSouce['outbound_business'] = outbound_business;
imgSouce['user_management'] = user_management;
imgSouce['change_password'] = change_password;
imgSouce['stock_search'] = stock_search;
imgSouce['commodity_management'] = commodity_management;
imgSouce['role_management'] = role_management;
//导出资源库
export default imgSouce;